# TODO: remove these if they don't change display behavior (likely auto-enabled by CONFIG_ZMK_DISPLAY)
CONFIG_ZMK_WIDGET_LAYER_STATUS=y
CONFIG_ZMK_WIDGET_BATTERY_STATUS=y
CONFIG_ZMK_WIDGET_OUTPUT_STATUS=y
